version: "3.9"

networks:
  potato_network:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    container_name: potato_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: potato
      POSTGRES_PASSWORD: 1234

    networks:
      - potato_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo
    container_name: potato_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: potato
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: todo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - potato_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: potato_zookeeper
    ports:
      - "2181:2181"
    networks:
      - potato_network

  kafka:
    image: wurstmeister/kafka
    container_name: potato_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - potato_network

volumes:
  postgres_data:
  mongo_data: