app:
  name: pkg
server:
  port: 8080

# gorm and postgresql
command:
  autoMigrate: true
  eventStoreDB:
    host: localhost
    port: 5432
    user: event_account
    password: 1234
    database: event_db
projector:
  kafka:
    bootstrapServers: localhost:9092
    topic: pkg
    consumerGroup: pkg
query:
  entityStoreDB:
    host: localhost
    port: 27017
    user: todo_account
    password: 1234
    database: todo_db
    autoMigrate: true
# profile (local, dev, alpha, stage, real)
profile:
  name: local